/** Catalogue content for the seed. Money is in whole dollars here and scaled to cents on insert. */

export interface SeedLot {
  auction: string;
  title: string;
  year: number;
  make: string;
  model: string;
  category: string;
  vin: string;
  mileage: number;
  engine: string;
  transmission: string;
  drivetrain: string;
  exterior: string;
  interior: string;
  location: string;
  summary: string;
  description: string;
  highlights: string[];
  flaws: string[];
  images: string[];
  estimate: [number, number];
  reserve: number | null;
  startingBid: number;
  featured?: boolean;
  /** Hours from seed time until the lot closes. Negative = already closed. */
  endsInHours: number;
  /** Hours from seed time until bidding opens. Negative = already open. */
  startsInHours: number;
  /** Roughly how much bidding activity to simulate. */
  heat: 0 | 1 | 2 | 3;
}

const img = (...names: string[]) => names.map((n) => `/cars/${n}.jpg`);

export const SEED_LOTS: SeedLot[] = [
  /* ───────────── The Hamptons Collector Sale ───────────── */
  {
    auction: "hamptons-collector-sale",
    title: "1963 Ferrari 250 GT Lusso",
    year: 1963,
    make: "Ferrari",
    model: "250 GT Lusso",
    category: "Classic",
    vin: "4879GT",
    mileage: 41_280,
    engine: "3.0L Tipo 168/62 V12",
    transmission: "4-Speed Manual",
    drivetrain: "RWD",
    exterior: "Rosso Corsa",
    interior: "Beige Connolly Leather",
    location: "Bridgehampton, NY",
    summary:
      "Classiche-certified, matching-numbers Lusso finished in its delivery colours after a four-year, no-expense-spared restoration.",
    description:
      "One of 350 Lusso examples built, this car was delivered new to Rome in March 1963 and remained in Italy until 1987. The current owner commissioned a complete bare-metal restoration completed in 2021, with the engine rebuilt by a marque specialist and the body refinished in its original Rosso Corsa over beige Connolly hide.\n\nFerrari Classiche certification confirms the car retains its original engine, gearbox and rear axle. The Lusso presents beautifully throughout and has been driven sparingly since the restoration, with roughly 900 shakedown miles covered. It is offered with its tool roll, jack, books and a comprehensive history file documenting the restoration in photographs and invoices.",
    highlights: [
      "Ferrari Classiche Red Book certified",
      "Matching-numbers engine, gearbox and rear axle",
      "Four-year bare-metal restoration completed 2021",
      "Original tool roll, jack and owner's manuals",
      "Documented ownership history from new",
    ],
    flaws: [
      "Light stone chipping to the front valance",
      "Period-correct radio is non-functional",
    ],
    images: img("ferrari-250", "int-luxury", "int-dash", "field-classics"),
    estimate: [1_650_000, 1_900_000],
    reserve: 1_575_000,
    startingBid: 950_000,
    featured: true,
    startsInHours: -72,
    endsInHours: 96,
    heat: 2,
  },
  {
    auction: "hamptons-collector-sale",
    title: "1970 Ford Mustang Boss 302",
    year: 1970,
    make: "Ford",
    model: "Mustang Boss 302",
    category: "Muscle",
    vin: "0F02G148822",
    mileage: 62_410,
    engine: "302ci Boss V8",
    transmission: "4-Speed Manual",
    drivetrain: "RWD",
    exterior: "Calypso Coral",
    interior: "Black Clarion Knit",
    location: "Bridgehampton, NY",
    summary:
      "Marti Report-verified Boss 302 with its original drivetrain, restored in 2019 and shown sparingly since.",
    description:
      "Finished in Calypso Coral over a black Clarion knit interior, this Boss 302 is documented by a Deluxe Marti Report confirming its original colour combination, Shaker hood delete and 3.50:1 Traction-Lok rear end.\n\nThe rotisserie restoration was completed in 2019 by a recognised Boss specialist in Pennsylvania. The 302ci engine was rebuilt to original specification with the correct Holley 780 carburettor and aluminium intake. The car has covered under 400 miles since and drives exactly as it should — crisp, loud and entirely honest.",
    highlights: [
      "Deluxe Marti Report included",
      "Numbers-matching 302ci Boss V8",
      "Rotisserie restoration completed 2019",
      "Original build sheet found under the rear seat",
      "Offered at no reserve",
    ],
    flaws: ["Minor orange peel in the driver's door paint", "Reproduction exhaust tips"],
    images: img("mustang-boss", "int-dash", "racetrack"),
    estimate: [140_000, 170_000],
    reserve: null,
    startingBid: 60_000,
    featured: true,
    startsInHours: -72,
    endsInHours: 5,
    heat: 3,
  },
  {
    auction: "hamptons-collector-sale",
    title: "2026 Aston Martin Vanquish Volante",
    year: 2026,
    make: "Aston Martin",
    model: "Vanquish Volante",
    category: "Modern Supercar",
    vin: "SCFRMFEV8SGR05112",
    mileage: 640,
    engine: "5.2L Twin-Turbo V12",
    transmission: "8-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Podium Green",
    interior: "Obsidian Black Semi-Aniline",
    location: "Sag Harbor, NY",
    summary:
      "Essentially new delivery-mileage Volante with £48,000 of Q by Aston Martin specification and full factory warranty.",
    description:
      "Delivered new in April 2026 and covered just 640 miles since. The specification runs to Podium Green paint, 21-inch satin forged wheels, carbon-fibre roll hoop finishers, the Bowers & Wilkins audio upgrade and a full carbon exterior pack.\n\nThe balance of the manufacturer warranty transfers to the buyer, and the car has had its pre-delivery inspection and first service completed at the selling dealer. Two keys, all literature and the fitted luggage set are included.",
    highlights: [
      "640 delivery miles from new",
      "Extensive Q by Aston Martin specification",
      "Balance of factory warranty transfers",
      "Carbon exterior pack and 21-inch forged wheels",
      "Two keys, books and fitted luggage",
    ],
    flaws: ["Protective film on the sills has a small lifted edge"],
    images: img("aston-vanquish", "int-cockpit", "neon-tunnel"),
    estimate: [450_000, 520_000],
    reserve: 442_000,
    startingBid: 300_000,
    featured: true,
    startsInHours: -72,
    endsInHours: -18,
    heat: 3,
  },
  {
    auction: "hamptons-collector-sale",
    title: "2023 Bentley Continental GT Speed",
    year: 2023,
    make: "Bentley",
    model: "Continental GT Speed",
    category: "Grand Tourer",
    vin: "SCBCG2ZG8PC004471",
    mileage: 7_820,
    engine: "6.0L Twin-Turbo W12",
    transmission: "8-Speed Dual-Clutch",
    drivetrain: "AWD",
    exterior: "Onyx",
    interior: "Beluga / Hotspur Hide",
    location: "East Hampton, NY",
    summary:
      "Final-series W12 Speed with the Mulliner Driving Specification, rear-wheel steering and carbon ceramic brakes.",
    description:
      "One of the last Continental GTs built with the twelve-cylinder engine, specified from new with the Mulliner Driving Specification, Touring Pack, Naim audio and carbon ceramic brakes.\n\nThe car has been serviced exclusively at Bentley Long Island and presents as new inside and out. Front paint protection film was applied before delivery and remains in place. A rare combination of the last great W12 and genuinely low mileage.",
    highlights: [
      "Final-series 650bhp W12 engine",
      "Mulliner Driving Specification and Touring Pack",
      "Carbon ceramic brakes, rear-wheel steering",
      "Full Bentley main-dealer service history",
      "Paint protection film from new",
    ],
    flaws: ["Light wheel rash on the near-side rear rim"],
    images: img("bentley-front", "int-luxury", "int-rear-seats"),
    estimate: [225_000, 265_000],
    reserve: 218_000,
    startingBid: 145_000,
    startsInHours: -72,
    endsInHours: -30,
    heat: 2,
  },
  {
    auction: "summer-classics-2026",
    title: "1969 Mercedes-Benz 280 SE Coupe",
    year: 1969,
    make: "Mercedes-Benz",
    model: "280 SE Coupe",
    category: "Classic",
    vin: "11102112003887",
    mileage: 88_900,
    engine: "2.8L M130 Inline-Six",
    transmission: "4-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Light Ivory",
    interior: "Cognac MB-Tex",
    location: "Bridgehampton, NY",
    summary:
      "California-delivered W111 coupe in its original Light Ivory, restored over three years with a rebuilt engine.",
    description:
      "A genuinely handsome W111 coupe, delivered new to Pasadena in 1969 and kept in dry Southern California storage for most of its life. The restoration, completed in 2022, included a full repaint in the original Light Ivory, a rebuilt M130 engine and new chrome throughout.\n\nThe wood veneers were professionally refinished and the MB-Tex interior is believed original and remarkably well preserved. The car runs and drives superbly, with the smooth, unhurried character these coupes are prized for.",
    highlights: [
      "Original Light Ivory over cognac",
      "Engine rebuilt during 2022 restoration",
      "Refinished wood veneers, new chrome",
      "Believed-original interior in excellent order",
      "Documented California history",
    ],
    flaws: ["Hairline crack in the dash top", "Clock is intermittent"],
    images: img("mercedes-280se", "int-rear-seats", "int-dash"),
    estimate: [95_000, 120_000],
    reserve: 92_000,
    startingBid: 45_000,
    startsInHours: -2208,
    endsInHours: -2160,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "1994 Mazda RX-7 Touring",
    year: 1994,
    make: "Mazda",
    model: "RX-7 (FD)",
    category: "Modern Classic",
    vin: "JM1FD3312R0302991",
    mileage: 54_300,
    engine: "1.3L Twin-Turbo 13B-REW Rotary",
    transmission: "5-Speed Manual",
    drivetrain: "RWD",
    exterior: "Montego Blue Mica",
    interior: "Black Leather",
    location: "Southampton, NY",
    summary:
      "Unmodified, two-owner FD with a fresh rotary rebuild and complete service records from new.",
    description:
      "FD RX-7s have been comprehensively ruined by modification, which makes a stock, two-owner Touring car genuinely hard to find. This one retains its sequential twin-turbo system, factory airbox and original ECU.\n\nThe engine was rebuilt at 51,000 miles by a rotary specialist in Connecticut with new apex seals, bearings and a rebuilt turbo system. All work is documented. The car comes with its original window sticker, both keys and the full set of books.",
    highlights: [
      "Entirely unmodified, factory twin-turbo system",
      "Rotary rebuilt at 51,000 miles by a specialist",
      "Two owners from new with full records",
      "Original window sticker and both keys",
      "Offered at no reserve",
    ],
    flaws: [
      "Common fading to the rear bumper plastic",
      "Driver's seat bolster shows light wear",
    ],
    images: img("mazda-rx7", "int-cockpit", "racetrack"),
    estimate: [55_000, 70_000],
    reserve: null,
    startingBid: 25_000,
    startsInHours: -2208,
    endsInHours: -2162,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "1961 Ford Ranchero",
    year: 1961,
    make: "Ford",
    model: "Ranchero",
    category: "Classic",
    vin: "1K27F148903",
    mileage: 71_050,
    engine: "170ci Inline-Six",
    transmission: "3-Speed Manual",
    drivetrain: "RWD",
    exterior: "Monte Carlo Red",
    interior: "Red and White Vinyl",
    location: "Bridgehampton, NY",
    summary:
      "Charming survivor-grade Ranchero repainted in its original Monte Carlo Red, running and driving well.",
    description:
      "A straightforward, honest Ranchero that has been repainted once in its original colour and otherwise left alone. The 170ci six starts readily and pulls cleanly, and the three-speed shifts without complaint.\n\nThis is not a show car and is not presented as one. It is a usable, likeable piece of early-sixties Americana that will draw a crowd at any village green it parks on.",
    highlights: [
      "Original colour combination",
      "Running, driving, usable condition",
      "Bed wood replaced in 2023",
      "New tyres, brakes and exhaust",
      "Offered at no reserve",
    ],
    flaws: [
      "Surface rust visible in the spare wheel well",
      "Chrome bumpers show pitting",
      "Heater fan does not work",
    ],
    images: img("ranchero", "truck-bw", "int-dash"),
    estimate: [38_000, 48_000],
    reserve: null,
    startingBid: 15_000,
    startsInHours: -2208,
    endsInHours: -2164,
    heat: 2,
  },
  {
    auction: "summer-classics-2026",
    title: "1972 Chevrolet C10 Shortbed",
    year: 1972,
    make: "Chevrolet",
    model: "C10",
    category: "Truck",
    vin: "CCE142S139877",
    mileage: 96_440,
    engine: "350ci V8",
    transmission: "3-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Dark Green Metallic",
    interior: "Saddle Vinyl",
    location: "Water Mill, NY",
    summary:
      "Short-bed C10 restomod on air ride with a crate 350, disc brakes and a tastefully restrained interior.",
    description:
      "Built over two years by its current owner, this C10 pairs the right look with genuinely useful upgrades: a crate 350 with an Edelbrock intake, four-wheel disc brakes, an air ride system and a modern stereo hidden behind the original dash face.\n\nThe bed is lined in finished oak with polished stainless strips. It is a comfortable, torquey, easy truck to drive, and the restraint shown in the build is what sets it apart from most.",
    highlights: [
      "Crate 350ci V8 with Edelbrock induction",
      "Air ride suspension, four-wheel disc brakes",
      "Finished oak bed with stainless strips",
      "Discreet modern audio behind original dash",
      "Built over two years, receipts included",
    ],
    flaws: ["Air compressor is audible in the cab", "Tailgate has a small dent on the lower lip"],
    images: img("truck-bw", "truck-camper", "int-dash"),
    estimate: [45_000, 58_000],
    reserve: 44_000,
    startingBid: 22_000,
    startsInHours: -2208,
    endsInHours: -2166,
    heat: 2,
  },
  {
    auction: "summer-classics-2026",
    title: "1968 Lincoln Continental Sedan",
    year: 1968,
    make: "Lincoln",
    model: "Continental",
    category: "Classic",
    vin: "8Y82G810442",
    mileage: 79_300,
    engine: "462ci V8",
    transmission: "3-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Wimbledon White",
    interior: "Black Leather",
    location: "Bridgehampton, NY",
    summary:
      "Suicide-door Continental with working power everything and a recent mechanical recommissioning.",
    description:
      "The last of the great suicide-door Continentals, this 1968 sedan has been recommissioned mechanically over the past eighteen months: fuel system, brakes, suspension bushings, and a rebuilt power window system that now works on all four doors — a rarity.\n\nThe paint is older and shows its age up close, but the car has real presence and drives with the effortless float these were built for.",
    highlights: [
      "All four power windows working",
      "Comprehensive mechanical recommissioning",
      "462ci V8 runs strongly",
      "Rare working factory air conditioning",
      "Extensive invoices from the past two years",
    ],
    flaws: [
      "Older respray with visible polishing marks",
      "Vinyl roof has one small bubble",
      "Radio does not receive FM",
    ],
    images: img("sedan-bw", "int-rear-seats", "int-luxury"),
    estimate: [40_000, 52_000],
    reserve: 38_500,
    startingBid: 18_000,
    startsInHours: -2208,
    endsInHours: -2168,
    heat: 1,
  },
  {
    auction: "hamptons-collector-sale",
    title: "2024 Chevrolet Corvette Z06",
    year: 2024,
    make: "Chevrolet",
    model: "Corvette Z06",
    category: "Modern Supercar",
    vin: "1G1YG2D42P5600318",
    mileage: 3_140,
    engine: "5.5L LT6 Flat-Plane V8",
    transmission: "8-Speed Dual-Clutch",
    drivetrain: "RWD",
    exterior: "Amplify Orange Tintcoat",
    interior: "Jet Black",
    location: "Southampton, NY",
    summary: "3Lz Z06 with the Z07 Performance Package, carbon wheels and carbon ceramic brakes.",
    description:
      "Specified with the Z07 Performance Package, carbon-fibre wheels, carbon ceramic brakes and the carbon aero package — effectively the most capable configuration offered.\n\nWith 3,140 miles it is barely broken in. The LT6 is the highest-revving V8 ever fitted to a production car and sounds like nothing else on the road. Both keys, the window sticker and all literature accompany the car.",
    highlights: [
      "Z07 Performance Package",
      "Carbon-fibre wheels and carbon ceramic brakes",
      "Full carbon aero package",
      "3,140 miles from new",
      "Window sticker and both keys",
    ],
    flaws: ["Front splitter has light scuffing from a driveway"],
    images: img("corvette-c8", "int-wheel", "racetrack"),
    estimate: [135_000, 155_000],
    reserve: 128_000,
    startingBid: 85_000,
    startsInHours: -72,
    endsInHours: -42,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "2021 Audi RS6 Avant",
    year: 2021,
    make: "Audi",
    model: "RS6 Avant",
    category: "Performance Wagon",
    vin: "WUA1CBF24MN901337",
    mileage: 19_600,
    engine: "4.0L Twin-Turbo V8",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    exterior: "Nardo Grey",
    interior: "Black Valcona Leather",
    location: "Montauk, NY",
    summary:
      "Nardo Grey RS6 with the Executive and Dynamic packages, ceramic brakes and 22-inch wheels.",
    description:
      "The wagon that finally made it to the United States, specified here in the colour everybody wanted. The Executive and Dynamic packages bring the Bang & Olufsen 3D audio, head-up display, dynamic ride control and rear-wheel steering.\n\nServiced on schedule at Audi Southampton, with no accident history and clean Carfax. A genuinely fast car that will also take four people and a dog to Montauk without complaint.",
    highlights: [
      "Nardo Grey over black Valcona",
      "Executive and Dynamic packages",
      "Ceramic brakes, 22-inch wheels",
      "Clean Carfax, no accidents",
      "Audi main-dealer service history",
    ],
    flaws: ["Curb rash on the front near-side wheel", "Small chip on the leading edge of the bonnet"],
    images: img("wagon-studio", "int-cockpit", "int-rear-seats"),
    estimate: [105_000, 125_000],
    reserve: 98_000,
    startingBid: 62_000,
    startsInHours: -2208,
    endsInHours: -2170,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "1991 Honda Prelude Si 4WS",
    year: 1991,
    make: "Honda",
    model: "Prelude Si",
    category: "Modern Classic",
    vin: "JHMBA4149MC010228",
    mileage: 108_700,
    engine: "2.1L B21A1 Inline-Four",
    transmission: "5-Speed Manual",
    drivetrain: "FWD",
    exterior: "Tahitian Green Pearl",
    interior: "Grey Cloth",
    location: "Sag Harbor, NY",
    summary:
      "Rust-free, one-family third-generation Prelude with the mechanical four-wheel-steering system intact and working.",
    description:
      "Bought new by the current owner's father in Pennsylvania and kept in the family since. The mechanical four-wheel-steering system — the clever one, before Honda went electronic — works exactly as intended.\n\nThe car is unmolested and rust-free, having spent every winter since 1998 in a heated garage. A timing belt, water pump and full fluid service were completed in 2025. These are rising quickly and clean examples have essentially stopped appearing.",
    highlights: [
      "Original mechanical 4WS system working correctly",
      "One family from new, rust-free",
      "Timing belt and water pump done in 2025",
      "Original radio, books and spare key",
      "Offered at no reserve",
    ],
    flaws: [
      "Clear coat failing on the roof panel",
      "Driver's window is slow",
      "Air conditioning needs a recharge",
    ],
    images: img("prelude-classic", "int-dash", "int-cockpit"),
    estimate: [22_000, 30_000],
    reserve: null,
    startingBid: 8_000,
    startsInHours: -2208,
    endsInHours: -2172,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "2022 Maserati MC20",
    year: 2022,
    make: "Maserati",
    model: "MC20",
    category: "Modern Supercar",
    vin: "ZN6PUAAS8N1375004",
    mileage: 4_430,
    engine: "3.0L Nettuno Twin-Turbo V6",
    transmission: "8-Speed Dual-Clutch",
    drivetrain: "RWD",
    exterior: "Bianco Audace",
    interior: "Nero Alcantara",
    location: "East Hampton, NY",
    summary:
      "Carbon-tubbed MC20 with the carbon exterior package, lift system and matching luggage.",
    description:
      "Maserati's return to the supercar class, built around a carbon-fibre monocoque and the pre-chamber Nettuno V6. This car carries the carbon exterior package, the front axle lift, carbon-fibre interior trim and the Sonus faber audio system.\n\nFour thousand miles from new, serviced on schedule, and offered with the full set of fitted luggage, both keys and the car cover.",
    highlights: [
      "Carbon-fibre monocoque chassis",
      "Carbon exterior and interior packages",
      "Front axle lift system",
      "Fitted luggage set and car cover",
      "4,430 miles, serviced on schedule",
    ],
    flaws: ["Small stone chip on the leading edge of the roof"],
    images: img("maserati-drift", "int-cockpit", "neon-tunnel"),
    estimate: [195_000, 225_000],
    reserve: 188_000,
    startingBid: 125_000,
    startsInHours: -2208,
    endsInHours: -2174,
    heat: 2,
  },
  {
    auction: "summer-classics-2026",
    title: "2023 Lexus LC 500 Coupe",
    year: 2023,
    make: "Lexus",
    model: "LC 500",
    category: "Grand Tourer",
    vin: "JTHHPAAY4PA010552",
    mileage: 11_240,
    engine: "5.0L 2UR-GSE V8",
    transmission: "10-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Obsidian",
    interior: "Circuit Red Semi-Aniline",
    location: "Bridgehampton, NY",
    summary:
      "Naturally aspirated V8 LC 500 with the Touring package, Mark Levinson audio and glass roof.",
    description:
      "One of the last naturally aspirated V8 grand tourers anybody will build, and arguably the best-looking car Lexus has produced. This example carries the Touring package, Mark Levinson reference audio and the glass roof.\n\nA single owner from new with Lexus service history and a clean Carfax. The 2UR-GSE engine is as unburstable as everything else Lexus makes, which makes this an unusually sensible way to own something genuinely special.",
    highlights: [
      "Naturally aspirated 5.0L V8",
      "Touring package with Mark Levinson audio",
      "Glass panoramic roof",
      "One owner, full Lexus service history",
      "Clean Carfax",
    ],
    flaws: ["Light swirl marks in the black paint under direct sun"],
    images: img("mazda-concept", "int-luxury", "int-wheel"),
    estimate: [85_000, 98_000],
    reserve: 82_000,
    startingBid: 48_000,
    startsInHours: -2208,
    endsInHours: -2176,
    heat: 3,
  },

  /* ───────────── Modern Performance | Online Only ───────────── */
  {
    auction: "modern-performance-online",
    title: "2025 Mercedes-AMG S 63 E Performance",
    year: 2025,
    make: "Mercedes-Benz",
    model: "AMG S 63 E Performance",
    category: "Luxury Sedan",
    vin: "W1K6G8DB1SA290114",
    mileage: 6_310,
    engine: "4.0L Twin-Turbo V8 Plug-In Hybrid",
    transmission: "9-Speed Automatic",
    drivetrain: "AWD",
    exterior: "Obsidian Black Metallic",
    interior: "Nappa Exclusive Black",
    location: "Greenwich, CT",
    summary:
      "802-horsepower hybrid AMG flagship with the Executive rear seat package and AMG ceramic brakes.",
    description:
      "The most powerful S-Class ever built, combining the hand-assembled 4.0 twin-turbo V8 with a rear-axle electric motor for 802 horsepower and a sub-three-second sprint.\n\nSpecified with the Executive rear seat package, AMG ceramic composite brakes, rear-axle steering and the Burmester 4D sound system. Under warranty until 2029 and serviced by Mercedes-Benz of Greenwich.",
    highlights: [
      "802hp hybrid AMG powertrain",
      "Executive rear seat package",
      "AMG ceramic composite brakes",
      "Burmester 4D surround sound",
      "Factory warranty to 2029",
    ],
    flaws: ["Rear bumper has a small scuff from a parking sensor failure, since repaired"],
    images: img("amg-s63", "int-luxury", "int-rear-seats"),
    estimate: [185_000, 210_000],
    reserve: 178_000,
    startingBid: 115_000,
    featured: true,
    startsInHours: -2556,
    endsInHours: -2520,
    heat: 3,
  },
  {
    auction: "modern-performance-online",
    title: "2021 Jaguar F-Type R Coupe",
    year: 2021,
    make: "Jaguar",
    model: "F-Type R",
    category: "Sports Car",
    vin: "SAJD51E64MCK72210",
    mileage: 14_880,
    engine: "5.0L Supercharged V8",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    exterior: "Caldera Red",
    interior: "Ebony Windsor Leather",
    location: "Rye, NY",
    summary: "575hp supercharged F-Type R with the performance seats and switchable exhaust.",
    description:
      "The facelifted F-Type R, with the supercharged 5.0 V8 making 575 horsepower and one of the best exhaust notes money can buy. Specified in Caldera Red with the performance seats, switchable exhaust, and the Meridian surround system.\n\nTwo owners, clean Carfax, and Jaguar service history. These have found their floor and started climbing; a V8 coupe in a proper colour is the one to own.",
    highlights: [
      "575hp supercharged V8",
      "Switchable active exhaust",
      "Performance seats in Ebony Windsor",
      "Two owners, clean Carfax",
      "Jaguar main-dealer service history",
    ],
    flaws: ["Tyres are at roughly 40% and will need replacing within a year"],
    images: img("jaguar-ftype", "int-cockpit", "racetrack"),
    estimate: [62_000, 75_000],
    reserve: 58_000,
    startingBid: 32_000,
    startsInHours: -2556,
    endsInHours: -2522,
    heat: 3,
  },
  {
    auction: "modern-performance-online",
    title: "1999 Jaguar XKR Coupe",
    year: 1999,
    make: "Jaguar",
    model: "XKR",
    category: "Modern Classic",
    vin: "SAJGA41C2XMA20114",
    mileage: 68_200,
    engine: "4.0L Supercharged V8",
    transmission: "5-Speed Automatic",
    drivetrain: "RWD",
    exterior: "Carnival Yellow",
    interior: "Charcoal Leather",
    location: "Stamford, CT",
    summary:
      "Rare Carnival Yellow XKR with recent Nikasil-era engine checks and a comprehensive service file.",
    description:
      "An XKR in a colour that suits it far better than the endless silver cars, with a documented history and the engine checks these cars need. The supercharged AJ26 pulls hard and the gearbox shifts cleanly.\n\nAn enormous amount of car for the money, and finally beginning to be appreciated as the last of the properly analogue big Jaguars.",
    highlights: [
      "Rare Carnival Yellow over charcoal",
      "Supercharged 370hp V8",
      "Comprehensive service file",
      "Recent suspension refresh",
      "Offered at no reserve",
    ],
    flaws: [
      "Headliner is beginning to sag at the rear",
      "Wood trim shows lacquer crazing",
      "Both front seat bolsters are worn",
    ],
    images: img("jaguar-xk", "int-luxury", "int-dash"),
    estimate: [28_000, 36_000],
    reserve: null,
    startingBid: 9_000,
    startsInHours: -2556,
    endsInHours: -2524,
    heat: 2,
  },
  {
    auction: "modern-performance-online",
    title: "2023 Honda Civic Type R",
    year: 2023,
    make: "Honda",
    model: "Civic Type R",
    category: "Hot Hatch",
    vin: "SHHFL5H78PU200931",
    mileage: 8_910,
    engine: "2.0L Turbocharged VTEC",
    transmission: "6-Speed Manual",
    drivetrain: "FWD",
    exterior: "Championship White",
    interior: "Red Suede",
    location: "White Plains, NY",
    summary: "Championship White FL5 Type R, unmodified, with both keys and full documentation.",
    description:
      "The FL5 Type R in the colour it was designed for. Completely unmodified, which is increasingly unusual, and with under nine thousand miles.\n\nThe six-speed manual remains the best shifter fitted to any production car at any price. Serviced at Honda, clean Carfax, and offered with both keys, the window sticker and all literature.",
    highlights: [
      "Championship White, the signature Type R colour",
      "Completely unmodified",
      "6-speed manual with rev-match",
      "Under 9,000 miles",
      "Both keys and window sticker",
    ],
    flaws: ["Small rock chip on the front bumper"],
    images: img("type-r-white", "int-cockpit", "type-r-grey"),
    estimate: [48_000, 56_000],
    reserve: 45_000,
    startingBid: 28_000,
    startsInHours: -2556,
    endsInHours: -2526,
    heat: 3,
  },
  {
    auction: "modern-performance-online",
    title: "2024 Jeep Wrangler Rubicon 392",
    year: 2024,
    make: "Jeep",
    model: "Wrangler Rubicon 392",
    category: "SUV",
    vin: "1C4JJXSJ8RW200418",
    mileage: 9_740,
    engine: "6.4L HEMI V8",
    transmission: "8-Speed Automatic",
    drivetrain: "4WD",
    exterior: "Firecracker Red",
    interior: "Black Leather",
    location: "Riverhead, NY",
    summary: "470hp HEMI V8 Wrangler with the Xtreme Recon package and factory half doors.",
    description:
      "The V8 Wrangler, which Jeep has now discontinued, specified with the Xtreme Recon package, 35-inch tyres, the dual-door group and the Alpine audio system.\n\nUnmodified and never off-road beyond a beach permit. With the 392 out of production, clean low-mileage examples are already appreciating.",
    highlights: [
      "6.4L HEMI V8, now discontinued",
      "Xtreme Recon package with 35-inch tyres",
      "Dual door group including half doors",
      "Never off-roaded",
      "Under 10,000 miles",
    ],
    flaws: ["Soft top window has light clouding"],
    images: img("jeep-red", "int-dash", "suv-desert"),
    estimate: [78_000, 88_000],
    reserve: 74_000,
    startingBid: 45_000,
    startsInHours: -2556,
    endsInHours: -2528,
    heat: 2,
  },
  {
    auction: "modern-performance-online",
    title: "2026 BMW iX3 M Sport",
    year: 2026,
    make: "BMW",
    model: "iX3 M Sport",
    category: "Electric",
    vin: "WBY53EJ09SFR11204",
    mileage: 1_980,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    exterior: "Frozen Pure Grey",
    interior: "Veganza Black",
    location: "Manhasset, NY",
    summary: "Neue Klasse iX3 with the M Sport package, heat pump and 400-mile range.",
    description:
      "The first of BMW's Neue Klasse cars, with the 800-volt architecture that takes it from 10 to 80 percent in under twenty minutes. Specified with the M Sport package, panoramic roof, Harman Kardon audio and the heat pump.\n\nUnder two thousand miles and fully within the factory warranty, with the charging credit transferable to the buyer.",
    highlights: [
      "Neue Klasse platform, 800-volt architecture",
      "M Sport package and panoramic roof",
      "Heat pump for cold-weather efficiency",
      "Full factory warranty, transferable charging credit",
      "Under 2,000 miles",
    ],
    flaws: [],
    images: img("bmw-suv", "int-cockpit", "ev-studio"),
    estimate: [62_000, 72_000],
    reserve: 59_000,
    startingBid: 38_000,
    startsInHours: -2556,
    endsInHours: -2530,
    heat: 1,
  },
  {
    auction: "modern-performance-online",
    title: "2024 Tesla Model 3 Performance",
    year: 2024,
    make: "Tesla",
    model: "Model 3 Performance",
    category: "Electric",
    vin: "5YJ3E1EC8RF700221",
    mileage: 12_450,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    exterior: "Ultra Red",
    interior: "Black and White",
    location: "Brooklyn, NY",
    summary: "Refreshed Highland Performance with adaptive dampers, track mode and acceleration boost.",
    description:
      "The Highland-refresh Performance, which is a substantially better car than the one it replaced: adaptive damping, proper sport seats, and a genuinely quick 2.9-second sprint.\n\nOne owner, clean Carfax, full self-driving capability included and transferable. Still under the basic vehicle warranty.",
    highlights: [
      "Highland refresh with adaptive dampers",
      "Track mode and sport seats",
      "Full self-driving capability, transferable",
      "One owner, clean Carfax",
      "Under basic vehicle warranty",
    ],
    flaws: ["Light curb rash on one wheel", "Small scratch on the rear bumper"],
    images: img("tesla-m3", "int-wheel", "lineup"),
    estimate: [42_000, 49_000],
    reserve: null,
    startingBid: 24_000,
    startsInHours: -2556,
    endsInHours: -2532,
    heat: 3,
  },
  {
    auction: "modern-performance-online",
    title: "2024 Kia EV9 GT-Line",
    year: 2024,
    make: "Kia",
    model: "EV9 GT-Line",
    category: "Electric",
    vin: "KNDAEFS59R6020118",
    mileage: 15_600,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    exterior: "Ocean Blue Matte",
    interior: "Black Relaxion",
    location: "Garden City, NY",
    summary: "Three-row electric EV9 in GT-Line trim with the matte paint and second-row captain's chairs.",
    description:
      "The most convincing three-row electric SUV on sale, specified in GT-Line with the matte Ocean Blue finish, second-row relaxation captain's chairs, Meridian audio and the digital rear-view mirror.\n\nSeats six comfortably, tows 5,000lb, and charges at 800 volts. Balance of Kia's ten-year powertrain warranty transfers to the buyer.",
    highlights: [
      "GT-Line with matte Ocean Blue paint",
      "Second-row relaxation captain's chairs",
      "800-volt architecture",
      "Meridian premium audio",
      "Balance of 10-year powertrain warranty",
    ],
    flaws: ["Matte paint has a scuff on the rear quarter requiring specialist correction"],
    images: img("ev-studio", "int-rear-seats", "suv-teal"),
    estimate: [55_000, 62_000],
    reserve: 52_000,
    startingBid: 30_000,
    startsInHours: -2556,
    endsInHours: -2534,
    heat: 2,
  },

  /* ───────────── Winter Garage | January Sale (scheduled) ───────────── */
  {
    auction: "winter-garage-january",
    title: "2026 Honda Prelude",
    year: 2026,
    make: "Honda",
    model: "Prelude",
    category: "Sports Car",
    vin: "JHMKF1H70SC001042",
    mileage: 120,
    engine: "2.0L Hybrid",
    transmission: "e-CVT with S+ Shift",
    drivetrain: "FWD",
    exterior: "Winding Road Blue",
    interior: "Black",
    location: "Bridgehampton, NY",
    summary: "Delivery-mileage example of the reborn Prelude, consigned from a private collection.",
    description:
      "Honda's revival of the Prelude name, with the hybrid powertrain and the S+ Shift system that simulates a geared transmission. This is a delivery-mileage car from a collection that buys one of everything significant.\n\nOffered in January with full factory warranty and both keys.",
    highlights: [
      "120 delivery miles",
      "S+ Shift simulated-gear system",
      "Full factory warranty",
      "Private collection consignment",
      "Both keys and all literature",
    ],
    flaws: [],
    images: img("prelude-2026", "int-cockpit", "int-dash"),
    estimate: [38_000, 46_000],
    reserve: 36_000,
    startingBid: 22_000,
    startsInHours: 2400_400,
    endsInHours: 2520,
    heat: 0,
  },
  {
    auction: "winter-garage-january",
    title: "2027 Kia Telluride SX X-Line",
    year: 2027,
    make: "Kia",
    model: "Telluride SX X-Line",
    category: "SUV",
    vin: "5XYP5DGC8SG400882",
    mileage: 2_400,
    engine: "3.5L V6",
    transmission: "8-Speed Automatic",
    drivetrain: "AWD",
    exterior: "Wolf Grey",
    interior: "Black Nappa",
    location: "Bridgehampton, NY",
    summary: "Second-generation Telluride in top SX X-Line trim with the towing package.",
    description:
      "The redesigned Telluride, which carries over everything that made the first one the default choice and fixes the interior plastics. SX X-Line trim brings the Nappa leather, panoramic roof, head-up display and the 5,500lb tow package.\n\nAn easy, sensible family car offered in the January sale at a sensible reserve.",
    highlights: [
      "Top SX X-Line specification",
      "Nappa leather and panoramic roof",
      "5,500lb tow package",
      "Head-up display",
      "Under 2,500 miles",
    ],
    flaws: [],
    images: img("telluride", "int-rear-seats", "suv-dark"),
    estimate: [48_000, 55_000],
    reserve: 46_000,
    startingBid: 28_000,
    startsInHours: 2400_400,
    endsInHours: 2544,
    heat: 0,
  },
  {
    auction: "winter-garage-january",
    title: "2024 Chevrolet Blazer EV SS",
    year: 2024,
    make: "Chevrolet",
    model: "Blazer EV SS",
    category: "Electric",
    vin: "3GNKDJRK8RS200774",
    mileage: 7_300,
    engine: "Dual Motor Electric",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    exterior: "Radiant Red Tintcoat",
    interior: "Jet Black",
    location: "Bridgehampton, NY",
    summary: "615-horsepower Blazer EV SS with Wide Open Watts mode and the performance brake package.",
    description:
      "The quickest SS-badged Chevrolet ever built, with 615 horsepower in Wide Open Watts mode and a 3.4-second sprint. Specified with the performance brake package and the 22-inch wheels.\n\nOffered in the January sale with the balance of the factory warranty.",
    highlights: [
      "615hp in Wide Open Watts mode",
      "Performance brake package",
      "22-inch wheels",
      "Balance of factory warranty",
      "Under 7,500 miles",
    ],
    flaws: ["Light scuff on the lower front fascia"],
    images: img("blazer-red", "int-dash", "neon-tunnel"),
    estimate: [52_000, 60_000],
    reserve: null,
    startingBid: 30_000,
    startsInHours: 2400_400,
    endsInHours: 2568,
    heat: 0,
  },

  /* ───────────── Summer Classics 2026 (archive) ───────────── */
  {
    auction: "summer-classics-2026",
    title: "2022 Porsche 718 Cayman GTS 4.0",
    year: 2022,
    make: "Porsche",
    model: "718 Cayman GTS 4.0",
    category: "Sports Car",
    vin: "WP0AD2A86NS275119",
    mileage: 11_300,
    engine: "4.0L Flat-Six",
    transmission: "6-Speed Manual",
    drivetrain: "RWD",
    exterior: "Carrara White Metallic",
    interior: "Black Leather and Race-Tex",
    location: "Bridgehampton, NY",
    summary: "Naturally aspirated flat-six GTS 4.0 with the manual gearbox and PASM.",
    description:
      "The 718 everybody actually wanted: the naturally aspirated 4.0-litre flat-six with a six-speed manual. Sold in the Summer Classics sale to a bidder in Connecticut.",
    highlights: [
      "Naturally aspirated 4.0L flat-six",
      "6-speed manual gearbox",
      "PASM sport suspension",
      "Sport Chrono package",
    ],
    flaws: [],
    images: img("workshop", "int-cockpit", "racetrack"),
    estimate: [95_000, 110_000],
    reserve: 92_000,
    startingBid: 60_000,
    startsInHours: -2208_560,
    endsInHours: -2178,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "2024 Honda Civic Type R",
    year: 2024,
    make: "Honda",
    model: "Civic Type R",
    category: "Hot Hatch",
    vin: "SHHFL5H71RU204417",
    mileage: 6_100,
    engine: "2.0L Turbocharged VTEC",
    transmission: "6-Speed Manual",
    drivetrain: "FWD",
    exterior: "Sonic Grey Pearl",
    interior: "Red Suede",
    location: "Bridgehampton, NY",
    summary: "Sonic Grey FL5 Type R sold in the Summer Classics sale.",
    description:
      "An unmodified FL5 in Sonic Grey, sold to a bidder in New Jersey after sixty-one bids.",
    highlights: ["Unmodified", "6-speed manual", "Under 6,500 miles"],
    flaws: [],
    images: img("type-r-grey", "int-cockpit"),
    estimate: [46_000, 54_000],
    reserve: null,
    startingBid: 26_000,
    startsInHours: -2208_560,
    endsInHours: -2180,
    heat: 3,
  },
  {
    auction: "summer-classics-2026",
    title: "1988 Land Rover Defender 110",
    year: 1988,
    make: "Land Rover",
    model: "Defender 110",
    category: "SUV",
    vin: "SALLDHAF8AA450117",
    mileage: 104_200,
    engine: "3.5L V8",
    transmission: "5-Speed Manual",
    drivetrain: "4WD",
    exterior: "Coniston Green",
    interior: "Grey Vinyl",
    location: "Bridgehampton, NY",
    summary: "Galvanised-chassis Defender 110 that did not meet its reserve in the Summer sale.",
    description:
      "A properly restored 110 on a galvanised chassis. Bidding stopped short of the reserve and the lot was not sold; the consignor has since re-entered it for a future sale.",
    highlights: ["Galvanised chassis", "3.5L V8", "Restored 2021"],
    flaws: ["Did not meet reserve"],
    images: img("suv-desert", "truck-offroad", "int-dash"),
    estimate: [72_000, 88_000],
    reserve: 76_000,
    startingBid: 38_000,
    startsInHours: -2208_560,
    endsInHours: -2182,
    heat: 1,
  },
];
