/**
 * Rebuilds the demo database from scratch.
 *
 * Bid histories are generated by driving the real proxy-bidding engine rather
 * than inserting rows, so the ladders, soft-close extensions and reserve
 * outcomes in the demo are the ones the system actually produces.
 *
 *   npm run seed
 */
import fs from "node:fs";
import path from "node:path";

// Honour DATABASE_PATH so the container seeds the volume, not a stray local file.
const DB_FILE = process.env.DATABASE_PATH ?? path.join(process.cwd(), "data", "auction.db");
fs.mkdirSync(path.dirname(DB_FILE), { recursive: true });
for (const f of [DB_FILE, `${DB_FILE}-wal`, `${DB_FILE}-shm`]) {
  if (fs.existsSync(f)) fs.rmSync(f);
}

const { db } = await import("../src/lib/db");
const { createUser } = await import("../src/lib/users");
const { placeBid, increment, sweep } = await import("../src/lib/auction");
const { SEED_LOTS } = await import("./lots.mjs");
const { slugify } = await import("../src/lib/format");

const H = 3_600_000;
const T0 = Date.now();
const usd = (dollars: number) => Math.round(dollars * 100);

/* ── Accounts ───────────────────────────────────────────────── */

const admin = createUser({
  email: "admin@noreserveclassics.com",
  password: "admin1234",
  name: "Dana Whitlock",
  company: "No Reserve Classics",
  phone: "(800) 562-7815",
  role: "admin",
  bidder_status: "approved",
});

const demo = createUser({
  email: "broker@demo.com",
  password: "demo1234",
  name: "Jordan Reyes",
  company: "Reyes & Co. Real Estate",
  phone: "(631) 555-0142",
  bidder_status: "approved",
});

const PENDING = createUser({
  email: "pending@demo.com",
  password: "demo1234",
  name: "Sam Okafor",
  company: "Shoreline Partners",
  phone: "(631) 555-0177",
  bidder_status: "pending",
});

const BIDDER_NAMES: Array<[string, string, string]> = [
  ["m.calloway@example.com", "Marcus Calloway", "Calloway Residential"],
  ["t.ashford@example.com", "Thea Ashford", "Ashford Luxury Group"],
  ["r.devlin@example.com", "Ray Devlin", "Devlin Properties"],
  ["p.nakamura@example.com", "Priya Nakamura", "Harbor & Main"],
  ["l.ferraro@example.com", "Luca Ferraro", "Ferraro Estates"],
  ["g.whitman@example.com", "Grace Whitman", "Whitman Coastal"],
  ["d.osei@example.com", "Daniel Osei", "Osei Realty Partners"],
  ["n.brightwell@example.com", "Nina Brightwell", "Brightwell & Hall"],
  ["c.vandermeer@example.com", "Cass Vandermeer", "Vandermeer Group"],
  ["e.santoro@example.com", "Elena Santoro", "Santoro Modern"],
];

const bidders = BIDDER_NAMES.map(([email, name, company]) =>
  createUser({ email, password: "demo1234", name, company, bidder_status: "approved" }),
);
const pool = [demo, ...bidders];

console.log(`  accounts  ${pool.length + 2}`);

/* ── Auctions ───────────────────────────────────────────────── */

interface SeedAuction {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  venue: string;
  location: string;
  hero: string;
  startsInHours: number;
  endsInHours: number;
  premiumBps: number;
}

const H3 = -2160;   // three months ago
const H35 = -2520;  // roughly three and a half

const AUCTIONS: SeedAuction[] = [
  {
    slug: "hamptons-collector-sale",
    title: "The Hamptons Collector Sale",
    subtitle: "Columbus Day Weekend · Bridgehampton, New York",
    description:
      "Our flagship East End sale, running now at the Bridgehampton Historical Society grounds. Lots close one at a time through the weekend rather than all at once, so each car gets the room's full attention as it comes up.\n\nMost of this catalogue has already gone under the hammer. Two lots are still on the clock, and bidding on them is open to any approved bidder — online, by telephone, or from the floor.",
    venue: "Bridgehampton Historical Society",
    location: "Bridgehampton, NY",
    hero: "/cars/hero-wide.jpg",
    startsInHours: -72,
    endsInHours: 96,
    premiumBps: 1000,
  },
  {
    slug: "winter-garage-january",
    title: "Winter Garage",
    subtitle: "January Sale · Catalogue Open for Consignment",
    description:
      "Our January sale is now accepting consignments. Early entries are published as they are catalogued and inspected; bidding opens in the new year.",
    venue: "Online and Bridgehampton",
    location: "Bridgehampton, NY",
    hero: "/cars/ev-studio.jpg",
    startsInHours: 2_400,
    endsInHours: 2_568,
    premiumBps: 1000,
  },
  {
    slug: "summer-classics-2026",
    title: "Summer Classics",
    subtitle: "Results · July 2026",
    description:
      "Twelve lots offered over two days at Bridgehampton. Full hammer prices are published below for every lot, sold and unsold alike — we do not quietly remove the ones that did not find a buyer.",
    venue: "Bridgehampton Historical Society",
    location: "Bridgehampton, NY",
    hero: "/cars/field-classics.jpg",
    startsInHours: H3 - 48,
    endsInHours: H3,
    premiumBps: 1000,
  },
  {
    slug: "modern-performance-online",
    title: "Modern Performance",
    subtitle: "Results · Online Only, June 2026",
    description:
      "A timed online sale of late-model performance cars, electric flagships and modern classics. No floor and no paddle — lots closed on a rolling schedule with two-minute soft-close extensions throughout.",
    venue: "Online",
    location: "Tri-State Area",
    hero: "/cars/neon-tunnel.jpg",
    startsInHours: H35 - 36,
    endsInHours: H35,
    premiumBps: 800,
  },
];

const auctionIds = new Map<string, number>();
for (const a of AUCTIONS) {
  const starts = T0 + a.startsInHours * H;
  const ends = T0 + a.endsInHours * H;
  const status = T0 < starts ? "scheduled" : T0 > ends ? "ended" : "live";
  const info = db
    .prepare(
      `INSERT INTO auctions (slug, title, subtitle, description, venue, location, hero_image,
                             starts_at, ends_at, status, buyers_premium_bps, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    )
    .run(
      a.slug,
      a.title,
      a.subtitle,
      a.description,
      a.venue,
      a.location,
      a.hero,
      starts,
      ends,
      status,
      a.premiumBps,
      T0,
    );
  auctionIds.set(a.slug, info.lastInsertRowid as number);
}
console.log(`  auctions  ${AUCTIONS.length}`);

/* ── Lots ───────────────────────────────────────────────────── */

const counters = new Map<string, number>();
const lotIds: Array<{ id: number; heat: number; ends: number; title: string }> = [];

for (const l of SEED_LOTS) {
  const auctionId = auctionIds.get(l.auction);
  if (!auctionId) throw new Error(`Unknown auction: ${l.auction}`);

  const n = (counters.get(l.auction) ?? 0) + 1;
  counters.set(l.auction, n);
  const lotNo = String(n * 10).padStart(3, "0");

  const starts = T0 + l.startsInHours * H;
  const ends = T0 + l.endsInHours * H;
  const status = T0 < starts ? "scheduled" : "live";

  const info = db
    .prepare(
      `INSERT INTO lots (auction_id, lot_no, slug, title, year, make, model, category, vin, mileage,
                         engine, transmission, drivetrain, exterior, interior, location, summary,
                         description, highlights, flaws, images, estimate_low, estimate_high,
                         reserve, has_reserve, starting_bid, current_bid, bid_count, view_count,
                         starts_at, ends_at, status, featured, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 0, ?, ?, ?, ?, ?, ?)`,
    )
    .run(
      auctionId,
      lotNo,
      `${slugify(l.title)}-${lotNo}`,
      l.title,
      l.year,
      l.make,
      l.model,
      l.category,
      l.vin,
      l.mileage,
      l.engine,
      l.transmission,
      l.drivetrain,
      l.exterior,
      l.interior,
      l.location,
      l.summary,
      l.description,
      JSON.stringify(l.highlights),
      JSON.stringify(l.flaws),
      JSON.stringify(l.images),
      usd(l.estimate[0]),
      usd(l.estimate[1]),
      l.reserve == null ? null : usd(l.reserve),
      l.reserve == null ? 0 : 1,
      usd(l.startingBid),
      220 + Math.floor(Math.random() * 2_400),
      starts,
      ends,
      status,
      l.featured ? 1 : 0,
      T0,
    );

  lotIds.push({
    id: info.lastInsertRowid as number,
    heat: l.heat,
    ends,
    title: l.title,
  });
}
console.log(`  lots      ${lotIds.length}`);

/* ── Bid history, generated through the live engine ─────────── */

/**
 * Lots that have already closed need their bids recorded while the clock still
 * says they are open, so the window is temporarily rolled forward and then put
 * back before settlement.
 */
let bidsPlaced = 0;

for (const lot of lotIds) {
  if (lot.heat === 0) continue;

  const row = db.prepare(`SELECT * FROM lots WHERE id = ?`).get(lot.id) as {
    starting_bid: number;
    estimate_low: number;
    reserve: number | null;
    ends_at: number;
    starts_at: number;
  };

  const closed = lot.ends <= T0;
  if (closed) {
    // Reopen briefly so the engine will accept the historical bids.
    db.prepare(`UPDATE lots SET ends_at = ?, status = 'live' WHERE id = ?`).run(T0 + 48 * H, lot.id);
  }

  // Heat decides how deep into the estimate range the bidding runs.
  const target =
    lot.heat === 3
      ? row.estimate_low * (0.94 + Math.random() * 0.14)
      : lot.heat === 2
        ? row.estimate_low * (0.72 + Math.random() * 0.22)
        : row.estimate_low * (0.34 + Math.random() * 0.26);

  let current = row.starting_bid;
  let guard = 0;
  const participants = shuffle(pool).slice(0, 3 + lot.heat * 2);
  let i = 0;

  while (current < target && guard++ < 60) {
    const bidder = participants[i % participants.length]!;
    i++;
    // Bidders name a ceiling a little above where the price stands, which is
    // what produces realistic proxy duels rather than a tidy staircase.
    const ceiling = Math.round(
      current + increment(current) * (1 + Math.floor(Math.random() * 5)),
    );
    const res = placeBid({ lotId: lot.id, userId: bidder.id, maxAmount: ceiling });
    if (!res.ok) continue;
    bidsPlaced++;
    current = res.lot.current_bid;
  }

  if (closed) {
    db.prepare(`UPDATE lots SET ends_at = ?, starts_at = ? WHERE id = ?`).run(
      lot.ends,
      row.starts_at,
      lot.id,
    );
  } else {
    // Restore the intended close time, which soft-close extensions will have moved.
    db.prepare(`UPDATE lots SET ends_at = ? WHERE id = ?`).run(lot.ends, lot.id);
  }
}
console.log(`  bids      ${bidsPlaced}`);

// Settle everything whose clock has already run out, producing the archive.
const swept = sweep();
console.log(`  settled   ${swept.closed} lots closed, ${swept.opened} opened`);

/* ── Watchlist, comments, consignments, RSVPs ───────────────── */

const liveLots = db
  .prepare(`SELECT id, slug FROM lots WHERE status = 'live' ORDER BY ends_at LIMIT 6`)
  .all() as Array<{ id: number; slug: string }>;

for (const l of liveLots.slice(0, 4)) {
  db.prepare(`INSERT OR IGNORE INTO watchlist (user_id, lot_id, created_at) VALUES (?, ?, ?)`).run(
    demo.id,
    l.id,
    T0 - 2 * H,
  );
}

const COMMENTS: Array<[number, string]> = [
  [0, "Can the seller confirm whether the original jack and tool roll are present?"],
  [0, "Tool roll, jack and the original manuals are all included — photographed in the gallery, images 14 through 17."],
  [0, "Beautiful car. Is there any documentation of the Classiche process itself?"],
  [1, "What is the current mileage on the rebuilt engine?"],
  [1, "Just under 400 miles since the rebuild was completed in 2019."],
  [2, "Does the warranty transfer to an out-of-state buyer?"],
];

for (const [idx, body] of COMMENTS) {
  const lot = liveLots[idx];
  if (!lot) continue;
  const isAnswer = body.length > 90 && /included|miles since/.test(body);
  db.prepare(
    `INSERT INTO comments (lot_id, user_id, body, created_at) VALUES (?, ?, ?, ?)`,
  ).run(lot.id, isAnswer ? admin.id : pool[Math.floor(Math.random() * pool.length)]!.id, body, T0 - Math.floor(Math.random() * 20) * H);
}

const CONSIGNMENTS: Array<[string, string, number, string, string, string]> = [
  ["Walter Hensley", "whensley@example.com", 1967, "Chevrolet", "Corvette 427", "Numbers-matching, owned since 1992."],
  ["Marguerite Sobol", "msobol@example.com", 1973, "Porsche", "911 Carrera RS", "Touring spec, full history file."],
  ["Owen Tate", "otate@example.com", 2019, "McLaren", "600LT Spider", "6,000 miles, MSO paint."],
  ["Reema Chaudhry", "rchaudhry@example.com", 1985, "Ferrari", "308 GTS QV", "Belt service completed last month."],
];

for (const [name, email, year, make, model, notes] of CONSIGNMENTS) {
  db.prepare(
    `INSERT INTO consignments (name, email, phone, year, make, model, reserve_pref, notes, status, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(
    name,
    email,
    "(631) 555-0100",
    year,
    make,
    model,
    Math.random() > 0.5 ? "reserve" : "no-reserve",
    notes,
    "new",
    T0 - Math.floor(Math.random() * 200) * H,
  );
}

const hamptonsId = auctionIds.get("hamptons-collector-sale")!;
const RSVPS: Array<[string, string, string, number, string]> = [
  ["Alexis Moreau", "amoreau@example.com", "Moreau & Fane", 1, "bidding"],
  ["Preston Ivey", "pivey@example.com", "Ivey Coastal Realty", 2, "attending"],
  ["Hana Lindqvist", "hlindqvist@example.com", "Lindqvist Partners", 0, "bidding"],
  ["Desmond Park", "dpark@example.com", "Park Avenue East", 3, "attending"],
  ["Noor Haddad", "nhaddad@example.com", "Haddad Luxury Group", 1, "consigning"],
];

for (const [name, email, brokerage, guests, intent] of RSVPS) {
  db.prepare(
    `INSERT INTO rsvps (auction_id, name, email, phone, brokerage, guests, intent, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(hamptonsId, name, email, "(631) 555-0150", brokerage, guests, intent, T0 - Math.floor(Math.random() * 100) * H);
}

/* ── Summary ────────────────────────────────────────────────── */

const stats = db
  .prepare(
    `SELECT
       (SELECT COUNT(*) FROM lots)                      AS lots,
       (SELECT COUNT(*) FROM lots WHERE status='live')  AS live,
       (SELECT COUNT(*) FROM lots WHERE status='sold')  AS sold,
       (SELECT COUNT(*) FROM bids)                      AS bids,
       (SELECT COALESCE(SUM(current_bid),0) FROM lots WHERE status='sold') AS hammer`,
  )
  .get() as Record<string, number>;

console.log(`
  ───────────────────────────────────────────
  Seed complete.

  Lots          ${stats.lots}  (${stats.live} live, ${stats.sold} sold)
  Bids          ${stats.bids}
  Hammer total  $${Math.round(stats.hammer / 100).toLocaleString("en-US")}

  Admin    admin@noreserveclassics.com / admin1234
  Bidder   broker@demo.com        / demo1234
  Pending  pending@demo.com       / demo1234
  ───────────────────────────────────────────
`);

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j]!, a[i]!];
  }
  return a;
}
